# Generated by Django 2.1.2 on 2018-10-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('scan_datetime', models.DateTimeField(db_index=True)),
                ('create_datetime', models.DateTimeField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FileUnique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('size', models.IntegerField(db_index=True)),
                ('datetime', models.DateTimeField()),
                ('rights', models.CharField(max_length=12)),
                ('owner', models.CharField(max_length=20)),
                ('group', models.CharField(max_length=20)),
                ('sha1sum', models.CharField(db_index=True, max_length=40)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('comment', models.TextField()),
                ('disk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Disk')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Folder')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('level', models.IntegerField()),
                ('message', models.TextField()),
                ('comment', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.FileUnique'),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Folder'),
        ),
        migrations.AddField(
            model_name='disk',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Location'),
        ),
        migrations.AddField(
            model_name='disk',
            name='next_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Disk'),
        ),
    ]
