# Generated by Django 2.1.2 on 2018-10-27 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='disk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Disk'),
        ),
    ]
