# Generated by Django 2.1.1 on 2018-09-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0002_auto_20180929_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk',
            old_name='file_datetime',
            new_name='scan_datetime',
        ),
    ]
