# Generated by Django 2.1.1 on 2018-09-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0003_auto_20180929_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='disk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Disk'),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Folder'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='disk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Disk'),
        ),
    ]
