# Generated by Django 2.1.1 on 2018-10-06 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0006_auto_20181006_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='prev_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='import.Disk'),
        ),
    ]
