# Generated by Django 2.1.1 on 2018-10-07 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0007_auto_20181006_0810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disk',
            old_name='prev_version',
            new_name='next_version',
        ),
    ]
